[package]
name = "chap1-socket-programming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
env_logger = "0.9.0"
log = "0.4.14"
